name: opendrift_simon
channels:
  - opendrift
  - conda-forge
  - NOAA-ORR-ERD
dependencies:
  - python>=3.7
  - matplotlib>=3.1
  - numpy>=1.17
  - scipy>=1.6
  - netcdf4
  - ffmpeg
  - pyproj>=2.3
  - libgdal>=3.1
  - gdal>=3.1
  - xarray
  - dask
  - cfgrib
  - pygrib
  - xhistogram
  - requests
  - pytest
  - pytest-cov
  - pytest-benchmark
  - cartopy<0.20
  - nc-time-axis
  - geojson
  - opendrift-landmask-data
  - oil_library-opendrift>=4+noaa1.1.3
  - isodate
  - coloredlogs
  - cmocean
  - pip
  - xarray
  - dask
  - toolz 
  - pip:
    - motuclient