name: opendrift
channels:
  - opendrift
  - conda-forge
  - NOAA-ORR-ERD
dependencies:
  - python>=3.7
  - matplotlib>=3.1
  - numpy>=1.15.4
  - scipy>=1.2.0
  - netcdf4
  - ffmpeg
  - pyproj>=2.3
  - libgdal>=3.1
  - gdal>=3.1
  - xarray
  - dask
  - cfgrib
  - pygrib
  - xhistogram
  - requests
  - pytest
  - pytest-cov
  - pytest-benchmark
  - cartopy
  - nc-time-axis
  - geojson
  - opendrift-landmask-data
  - oil_library-opendrift>=2+noaa1.1.3
  - isodate
  - coloredlogs
  - pip
  - pip:
    - motuclient
